on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        set-safe-directory: '/github/workspace'
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v4
      with:
        dry_run: false
